# Generated by Django 6.0.2 on 2026-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='correo_empresarial',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
