# Generated by Django 6.0.2 on 2026-02-11 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('RECURSOS_HUMANOS', 'Recursos Humanos'), ('SUPERVISOR', 'Supervisor'), ('OPERARIO', 'Operario')], max_length=50)),
                ('trabajador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trabajador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
