# Generated by Django 6.0.2 on 2026-02-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_area_cargo_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='api.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='api.categoriatarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='api.cliente'),
        ),
    ]
