# Generated by Codex on 2026-02-26

from django.db import migrations, models


def forwards_map_roles(apps, schema_editor):
    PerfilUsuario = apps.get_model("api", "PerfilUsuario")
    PerfilUsuario.objects.filter(rol="RECURSOS_HUMANOS").update(rol="RRHH")
    PerfilUsuario.objects.filter(rol="OPERARIO").update(rol="TRABAJADOR")


def backwards_map_roles(apps, schema_editor):
    PerfilUsuario = apps.get_model("api", "PerfilUsuario")
    PerfilUsuario.objects.filter(rol="RRHH").update(rol="RECURSOS_HUMANOS")
    PerfilUsuario.objects.filter(rol="TRABAJADOR").update(rol="OPERARIO")


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_cliente_correo_cliente_descripcion_cliente_nombre_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_map_roles, backwards_map_roles),
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMINISTRADOR", "Administrador"),
                    ("RRHH", "RRHH"),
                    ("SUPERVISOR", "Supervisor"),
                    ("TRABAJADOR", "Trabajador"),
                ],
                max_length=50,
            ),
        ),
    ]
