# Generated by Codex on 2026-02-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_normalize_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoCliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo", models.FileField(upload_to="documentos_clientes/%Y/%m/")),
                ("nombre_original", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=20)),
                ("tamano_bytes", models.PositiveBigIntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_cliente_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="api.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoFinancieroCliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo_movimiento", models.CharField(choices=[("COSTO", "Costo"), ("INGRESO", "Ingreso")], max_length=10)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_financieros",
                        to="api.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_financieros_cliente_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="movimientofinancierocliente",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto__gt", 0)),
                name="movimiento_cliente_monto_gt_0",
            ),
        ),
    ]
