# Generated by Django 6.0.2 on 2026-02-28 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_documentocliente_movimientofinancierocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_herramienta', models.CharField(choices=[('INTERNO', 'Uso interno'), ('CLIENTE', 'Asignada a cliente')], default='INTERNO', max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADA', 'Asignada'), ('MANTENIMIENTO', 'Mantenimiento'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=20)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='api.cliente')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('fecha_orden', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('total_orden', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='api.proveedor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(choices=[('FABRICADO', 'Fabricacion propia'), ('COMPRADO', 'Comprado a proveedor')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='api.categoriaproducto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=14)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_orden_compra', to='api.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_OC', 'Entrada por orden de compra'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_resultante', models.PositiveIntegerField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_creados', to=settings.AUTH_USER_MODEL)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='api.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='api.producto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='producto_stock_actual_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='producto_stock_minimo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ordencompraitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='orden_compra_item_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ordencompraitem',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gt', 0)), name='orden_compra_item_costo_unitario_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ordencompraitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_linea__gt', 0)), name='orden_compra_item_total_linea_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ordencompraitem',
            constraint=models.UniqueConstraint(fields=('orden_compra', 'producto'), name='orden_compra_item_producto_unique'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movimiento_inventario_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(condition=models.Q(('total_orden__gte', 0)), name='orden_compra_total_gte_0'),
        ),
    ]
