# Generated by Django 6.0.2 on 2026-02-28 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_categoriaproducto_proveedor_herramienta_ordencompra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('DEVUELTA', 'Devuelta')], default='ACTIVA', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='herramienta',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='stock_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='herramienta',
            constraint=models.CheckConstraint(condition=models.Q(('stock_total__gte', 0)), name='herramienta_stock_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='herramienta',
            constraint=models.CheckConstraint(condition=models.Q(('stock_disponible__gte', 0)), name='herramienta_stock_disponible_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='herramienta',
            constraint=models.CheckConstraint(condition=models.Q(('stock_disponible__lte', models.F('stock_total'))), name='herramienta_stock_disponible_lte_total'),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_herramienta_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_herramientas', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='devuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_herramienta_devueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api.herramienta'),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_herramientas', to='api.trabajador'),
        ),
        migrations.AddConstraint(
            model_name='herramientaasignacion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='herramienta_asignacion_cantidad_gt_0'),
        ),
    ]
