# Generated by Django 6.0.2 on 2026-02-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_herramientaasignacion_herramienta_stock_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompraitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_orden_compra', to='api.producto'),
        ),
    ]
