# Generated by Django 6.0.2 on 2026-03-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_timesta_da87a7_idx',
            old_name='api_auditlo_timest_3e6c2d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_action_0a1743_idx',
            old_name='api_auditlo_action_5e9a3b_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_module_d06630_idx',
            old_name='api_auditlo_module_9f6f7b_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_model_bc6eb4_idx',
            old_name='api_auditlo_model_e7a978_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='api_auditlo_user_id_b0c441_idx',
            old_name='api_auditlo_user_id_0b788e_idx',
        ),
    ]
